routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\AdminController@index');
Route::get('/verify/{token}', 'V1\RegisterController@verify')->name('verify');
Auth::routes();

Route::get('/firebase', 'Web\FirebaseController@index');
Route::get('/check_location', 'Web\CoveredAreasController@check_location');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reset/{token}', 'V1\LoginController@reset')->name('reset');
Route::post('/reset', 'V1\LoginController@doReset')->name('do.reset');

Route::group(['prefix' => 'admin', 'middleware' => 'MultiTenant'], function () {
    Route::group(['prefix' => '/'], function () {
        Route::get('/', 'Web\AdminController@index')->name('dashboard');
        Route::get('update_language/{id}', 'Web\AdminController@update_language')->name('update_language');
        Route::get('update_language_dashboard/{id}', 'Web\AdminController@update_language_dashboard')->name('update_language_dashboard');
        Route::get('/profile', 'Web\AdminController@profile')->name('profile');
        Route::post('update/{id}', 'Web\AdminController@update')->name('admin.update');
        Route::get('/edit/{id}', 'Web\AdminController@edit')->name('admin.edit');
        Route::get('/login', 'Web\AdminController@login')->name('login');
        Route::post('/doLogin', 'Web\AdminController@doLogin')->name('doLogin');
        Route::get('/logout', 'Web\AdminController@logout')->name('admin_logout');
        Route::get('/trips', 'Web\AdminController@trips')->name('trips');
        Route::get('/trips/{id}', 'Web\AdminController@show')->name('trip_show');
        Route::get('/shipments', 'Web\AdminController@shipments')->name('shipments');
        Route::get('/shipments/{id}', 'Web\AdminController@show_shipment')->name('shipment_show');
    });
    Route::resource('/deals', 'Web\DealController');
    Route::post('/deals/{id}/change_status', 'Web\DealController@change_status');
    Route::resource('/contact_us', 'Web\ContactUsController');
    Route::post('/contact_us/{id}/change_status', 'Web\ContactUsController@change_status');
    Route::resource('/cms', 'Web\CMSController');

    Route::resource('/company_ads', 'Web\CompanyAdsController');
    Route::resource('/company_profile', 'Web\CompanyProfileController');
    Route::resource('/company_branches', 'Web\CompanyBranchController');

    Route::resource('/covered_areas', 'Web\CoveredAreasController');
    Route::get('create_covered_area', 'Web\CoveredAreasController@create_covered_area');

    Route::resource('/fixing_shops', 'Web\FixingShopsController');

    Route::resource('/cities', 'Web\CityController');
    Route::resource('/notifications', 'Web\NotificationsController');

    Route::resource('/users_push_setting', 'Web\PushController');

    Route::resource('/category_groups', 'Web\CategoryGroupController');
    Route::resource('/problem_types', 'Web\ProblemTypesController');
    Route::resource('/sos_requests', 'Web\SOSRequestsController');
    Route::get('show_on_map/{id}', 'Web\SOSRequestsController@show_on_map');

    Route::resource('/company_types', 'Web\CompanyTypesController');


    Route::resource('/emergency', 'Web\EmergencyController');

    Route::resource('/categories', 'Web\CategoryController');

    Route::resource('/admin_ads', 'Web\AdsController');

    Route::resource('/app_ads', 'Web\AppAdsController');

    Route::resource('/user', 'Web\UserController');
    Route::get('/user/{id}/trips', 'Web\UserController@trips');
    Route::get('/user/{id}/shipments', 'Web\UserController@shipments');
    Route::post('/user/{id}/add-role', 'Web\UserController@addRole');
    Route::resource('/faq', 'Web\FaqController');
    Route::resource('/contacts', 'Web\ContactsController');
    Route::resource('/settings', 'Web\SettingsController');
});

app/Http/Controllers/V1/NotificationController.php
<?php

namespace App\Http\Controllers\V1;

// firebase handler
use App\Exceptions\SOS\AreaNotCoveredException;
use App\Exceptions\SOS\NoCoveredAreasException;
use App\Helpers\NotificationsCenter;
use App\Helpers\NotificationUser;
use App\Helpers\PointLocation;
use App\Helpers\ResponseHandler;
use App\Http\Controllers\Controller;
use App\Http\Requests\SOSRequest\SOSRequestRequest;
use App\Http\Requests\SOSRequest\SOSRespondRequest;
use App\Http\Resources\SOSRequest\SOSRequestResource;
use App\Http\Resources\SOSRequest\SOSRespondResource;
use App\Model\CoveredArea;
use App\Model\Notifications;
use App\Model\ProblemType;
use Illuminate\Http\Request;
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;
use sngrl\PhpFirebaseCloudMessaging\Client;
use sngrl\PhpFirebaseCloudMessaging\Message;
use sngrl\PhpFirebaseCloudMessaging\Notification;
use sngrl\PhpFirebaseCloudMessaging\Recipient\Topic;

// single or multi devices
// topic
// end of firebase handler


class NotificationController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param SOSRequestRequest $request
     * @return \Illuminate\Http\Response
     */
    public function index(SOSRequestRequest $request)
    {
        if ($request->user_id == 0) {
            unset($request['user_id']);
        }

        if ($request->sos_problem_type_id == 0) {
            unset($request['sos_problem_type_id']);
        }
        $pointLocation = new PointLocation();
        $location = $request->location;
        $location = str_replace(' ', '', $location);
        $pieces = $pieces = explode(",", $location);
        $sos_lat = $pieces[0];
        $sos_long = $pieces[1];
        $points = array("$sos_lat $sos_long");
        $all_polygon = CoveredArea::all();
        $polygon_array = [];
        if (!empty($all_polygon)) {
            $i = 0;

            foreach ($all_polygon as $polygon) {
                $polygon = json_decode($polygon->area);


                $count = count($polygon) - 1;
                $first = true;
                $x = 0;
                foreach ($polygon as $poly) {
                    if ($first == true) {
                        $polygon_last = "$poly->lat $poly->lng";
                    }
                    $first = false;
                    $polygon_array[$i][] = "$poly->lat $poly->lng";

                    if ($x == $count) {
                        $polygon_array[$i][] = $polygon_last;
                    }
                    $x++;
                }
                $i++;
            }

        }

        if (!empty($polygon_array)) {
            $polygon = $polygon_array[0];//array("-50 30","50 70","100 50","80 10","110 -10","110 -30","-20 -50","-30 -40","10 -10","-10 10","-30 -20","-50 30");
            // The last point's coordinates must be the same as the first one's, to "close the loop"
            foreach ($points as $key => $point) {
                if ($pointLocation->pointInPolygon($point, $polygon) == 'outside') {
                    //return ResponseHandler::json('Your location not covered yet , thanks');
                    throw new AreaNotCoveredException;
                }
            }
        }

        $sos_request = \App\Model\SOSRequest::create($request->toArray());

        $sos_data = new SOSRequestResource($sos_request);
        //return $sos_data;
        // creata collection into RealTime DB with the request id,
        $firebase_url = env('FCM_URL', "https://haddaq-9e719.firebaseio.com/");
        $serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/haddaq-9e719-be0a1a884e99.json');
        $firebase = (new Factory)
            ->withServiceAccount($serviceAccount)
            ->withDatabaseUri($firebase_url)
            ->create();

        $database = $firebase->getDatabase();
        $collection_name = config('database.default') . '-sos_request-' . $sos_data->id;

        $sos_data = json_decode(json_encode($sos_data), true);
        $sos_data['collection_name'] = $collection_name;
        $sos_problem_type_details = $sos_data['sos_problem_type_details'];

        $database->getReference($collection_name)->push([
            'id' => $sos_data['id'],
            'user_id' => ($sos_data['user_id']) ? $sos_data['user_id'] : "0",
            'location' => $sos_data['location'],
            'name' => ($sos_data['user_id']) ? $sos_data['user_details']['name'] : "Guest",
            'mobile' => $sos_data['mobile'],//$sos_data->mobile,

        ]);
        $send_data = array(
            'type' => 'new_request',
            'collection_name' => $collection_name,
            'id' => $sos_data['id'],
            'user_id' => ($sos_data['user_id']) ? $sos_data['user_id'] : "0",
            'user_details' => $sos_data['user_details'],
            'name' => ($sos_data['user_id']) ? $sos_data['user_details']['name'] : "Guest",
            'mobile' => $sos_data['mobile'],//$sos_data->mobile,
            'location' => $sos_data['location'],// $sos_data->location,
            'device_udid' => $sos_data['device_udid'],// $sos_data->device_udid,
            'push_token' => $sos_data['push_token'],//$sos_data->push_token,
            'sos_problem_type_id' => $sos_data['sos_problem_type_id'],//$sos_data->sos_problem_type_id,
            'sos_problem_type_details' => $sos_problem_type_details,
            "problem_type" => ($sos_data['sos_problem_type_id']) ? $sos_problem_type_details['problem_type_en'] : "Other",
            "problem_type_ar" => ($sos_data['sos_problem_type_id']) ? $sos_problem_type_details['problem_type_ar'] : "Other",
            'description' => ($sos_data['description']) ? $sos_data['description'] : "",
            'sos_request_status' => 'Opening'
        );
        $notification_center = new NotificationsCenter();
        $not_title = $send_data['name'] . ' Requested SOS Request';
        $sos_problem_type = ProblemType::find($sos_data['sos_problem_type_id']);

        $notification_center->createNotification($send_data['type'], $sos_problem_type->problem_type
            , $send_data['location'], $send_data["collection_name"], $send_data["id"]);

        $server_key = env('FCM_SERVER_KEY', '');

        $client = new Client();
        $client->setApiKey($server_key);
        $client->injectGuzzleHttpClient(new \GuzzleHttp\Client());

        $message = new Message();
        $message->setPriority('high');

        $message_topic = config('database.default') . "-RegularUsersAndFreeSaviors";
        $message->addRecipient(new Topic($message_topic));

        $notification = new Notification('HaddaQ', 'New SOS Request');
        $notification->setTitle('HaddaQ')
            ->setSound('haddaq.wav')
            ->setBody('New SOS Request');

        $message
            ->setNotification($notification)
            ->setData($send_data);

        $response = $client->send($message);

        return ResponseHandler::json($sos_data);

    }

    public function respond_sos_request(SOSRespondRequest $request)
    {
        $id = $request->sos_request_id;
        $sos_request = \App\Model\SOSRequest::find($id);
        if (!$sos_request) {
            return ResponseHandler::json('false');
        }

        if ($sos_request->sos_request_status == 'Closed') {
            return ResponseHandler::json('Request Closed , Thanks');
        }

        $user_id = $request->user_id;
        $sos_response = \App\Model\SOSResponse::where(['id' => $id, 'user_id' => $user_id])->first();

        if (!empty($sos_response)) {
            return ResponseHandler::json('You Respond To This Request Before , Thanks');
        }
        //return $sos_response;
        $sos_request = \App\Model\SOSResponse::create($request->toArray());
        $collection_name = config('database.default') . '-sos_request-' . $sos_request->id;
        $data = new SOSRespondResource($sos_request);
        $data = json_decode(json_encode($data), true);
        $send_data = array(
            'type' => 'respond_request',
            'id' => $data['id'],
            'user_id' => ($data['user_id']) ? $data['user_id'] : "0",
            'savior_details' => $data['savior_details'],//$data->savior_details,
            'location' => $data['location'],//$data->location,
            'push_token' => $data['push_token'],// $data->push_token,
            'sos_request_id' => $data['sos_request_id'],//$data->sos_request_id,
            'sos_request_details' => $data['sos_request_details'],//$data->sos_request,
            'response_status' => $data['response_status'],//$data->response_status,
        );
        try{
            // return $send_data;
            $server_key = env('FCM_SERVER_KEY', '');

            $client = new Client();
            $client->setApiKey($server_key);
            $client->injectGuzzleHttpClient(new \GuzzleHttp\Client());

            $message = new Message();
            $message->setPriority('high');

            $message->addRecipient(new Topic($collection_name));

            $notification = new Notification('HaddaQ', 'Respond To Request');
            $notification->setTitle('HaddaQ')
                ->setSound('haddaq.wav')
                ->setBody('Respond To Request');

            $message
                ->setNotification($notification)
                ->setData($send_data);

            $response = $client->send($message);
        }
        catch (\Exception $e){
            return ResponseHandler::json($e->getMessage());
        }

        return ResponseHandler::json($data);
    }

    public function close_sos_request(Request $request, $id)
    {
        $sos_request = \App\Model\SOSRequest::find($id);
        if (!$sos_request) {
            return ResponseHandler::json('false');
        }

        if ($sos_request->sos_request_status == 'Closed') {
            return ResponseHandler::json('Request Already Closed , Thanks');
        }

        $update_status = array('sos_request_status' => 'Closed', 'closed_by' => 'Owner');

resources/views/admin/notifications/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						@lang('labels.admin.send_notifications_to_all')
					</div>
				</div>
				<div class="panel-body">
					<form  enctype="multipart/form-data" method="POST" action="{{route('notifications.store')}}">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.title')</label>
						    <div class="col-sm-10" {{ $errors->has('title') ? ' has-error' : '' }}>
						    	@if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="title" placeholder="@lang('labels.please_enter') @lang('labels.title')"  required/>
						    </div>
						  </div>
				
					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.details')</label>
					    <div class="col-sm-10">
								@if ($errors->has('details'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('details') }}</strong>
                                    </span>
                                @endif
					    	<textarea class="form-control" placeholder="@lang('labels.details')" name="details" ></textarea>
					    </div>
					  </div>


					



					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
					   		<a href="{{route('notifications.index')}}" class="btn btn-default btn-block">@lang('labels.reset')</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">@lang('labels.admin.send_notifications')</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/notifications/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						Edit Fixing Shop
					</div>
				</div>
				<div class="panel-body">
					<form method="POST" enctype="multipart/form-data" action="{{action('Web\FixingShopsController@update', $fixing_shops->id)}}">
						<input type="hidden" name="_method" value="put" />
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<!-- cms type -->

					<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">English Name</label>
						    <div class="col-sm-10" {{ $errors->has('shop_name_en') ? ' has-error' : '' }}>
						    	@if ($errors->has('shop_name_en'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('shop_name_en') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="shop_name_en" placeholder="please enter Shop Name" value="{{$fixing_shops->shop_name_en}}" required/>
						    </div>
						  </div>
					  
					  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Arabic Name</label>
						    <div class="col-sm-10" {{ $errors->has('shop_name_ar') ? ' has-error' : '' }}>
						    	@if ($errors->has('shop_name_ar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('shop_name_ar') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="shop_name_ar" placeholder="please enter Arabic  Name" value="{{$fixing_shops->shop_name_ar}}"  required/>
						    </div>
						  </div>

					 

							
  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">Logo</label>
					    <div class="col-sm-10">
					    	<input type="file" class="form-control" placeholder="Category icon" name="images">
					    </div>
					  </div>

					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">Slider Images</label>
					    <div class="col-sm-10">
					    	<input type="file" class="form-control" placeholder="Slider Images" name="sliders[]" multiple >
					    </div>
					  </div>

						
					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">Type</label>
					    <div class="col-sm-10">
						<select class="form-control" name="fixing_shops_types_id" required="">
						<?php 
						if(!empty($fixing_shops_types)){
							foreach ($fixing_shops_types as $type) {?>
								<option <?php if($type->id == $fixing_shops->fixing_shops_types_id) echo "selected";?> value="<?php echo $type->id?>"><?php echo $type->type_name?></option>
							<?php }
						}
						?>
						</select>
					    </div>
					  </div>


					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">English Details</label>
					    <div class="col-sm-10">
					    	<textarea class="form-control" placeholder="English Details Content" name="about_en" >{{$fixing_shops->about_en}}</textarea>
					    </div>
					  </div>

					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">Arabic Details</label>
					    <div class="col-sm-10">
					    	<textarea class="form-control" placeholder="Arabic Details Content" name="about_ar" >{{$fixing_shops->about_ar}}</textarea>
					    </div>
					  </div>


					  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Phone</label>
						    <div class="col-sm-10" {{ $errors->has('mobile') ? ' has-error' : '' }}>
						    	@if ($errors->has('mobile'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('mobile') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="mobile" placeholder="please enter Phone Number" value="{{$fixing_shops->mobile}}"  required/>
						    </div>
						  </div>

						  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Email</label>
						    <div class="col-sm-10" {{ $errors->has('email') ? ' has-error' : '' }}>
						    	@if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
						    	<input type="email" class="form-control" name="email" placeholder="please enter Email "  value="{{$fixing_shops->email}}"  required/>
						    </div>
						  </div>

				 <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">City</label>
					    <div class="col-sm-10">
						<select class="form-control" name="city_id" required="">
						<?php 
						if(!empty($cities)){
							foreach ($cities as $type) {?>
								<option <?php if($type->id == $fixing_shops->city_id) echo "selected";?> value="<?php echo $type->id?>"><?php echo $type->name_en?></option>
							<?php }
						}
						?>
						</select>
					    </div>
					  </div>

					
					 <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Address in English</label>
						    <div class="col-sm-10" {{ $errors->has('address_en') ? ' has-error' : '' }}>
						    	@if ($errors->has('address_en'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address_en') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="address_en" placeholder="please enter English Address"  value="{{$fixing_shops->address_en}}" required/>
						    </div>
						  </div>

				 <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Address in Arabic</label>
						    <div class="col-sm-10" {{ $errors->has('address_ar') ? ' has-error' : '' }}>
						    	@if ($errors->has('address_ar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address_ar') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="address_ar" placeholder="please enter Arabic Address"  value="{{$fixing_shops->address_ar}}"  required/>
						    </div>
						  </div>
						  		  
		  
		   <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">Location (lat & Long seprated by comma ',')</label>
						    <div class="col-sm-10" {{ $errors->has('location') ? ' has-error' : '' }}>
						    	@if ($errors->has('location'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('location') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="location" placeholder="please enter Location" value="{{$fixing_shops->location}}"  required/>
						    </div>
						  </div>



					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
					   		<a href="{{route('fixing_shops.show',$fixing_shops->id)}}" class="btn btn-default btn-block">Back</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">Update</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/notifications/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12 col-md-offset-0">
			<div class="panel panel-default">
				<div class="panel-heading">Fixing Shops</div>
				<div class="panel-body">
					@include('admin.fixing_shops.search')
					<table class="table table-hover">
						<thead>
							<tr>
								<td colspan="5">
									<a href="{{route('fixing_shops.create')}}" class="btn btn-primary">+ New Fixing Shops</a>
								</td>
							</tr>
							<tr class="active">
								<th>#</th>
								<th>Arabic Name</th>
								<th>English Name</th>
								<th>Type</th>
							</tr>
						</thead>
						<tbody>
							<?php $i = 1 ;?>
							@if(isset($fixing_shops) && !empty($fixing_shops))
							@foreach($fixing_shops as $page)
							<tr  onclick="window.location='{{route('fixing_shops.show',$page->id)}}';" style="cursor : pointer">
								<td><?php echo $i ;?></td>
								<td>{{$page->shop_name_ar}}</td>
								<td>{{$page->shop_name_en}}</td>
								<td><?php
									switch ($page->fixing_shops_types_id) {
										case 1:
											echo "Gold";
											break;
										case 2:
											echo "Silver";
											break;
										case 3:
											echo "Bronze";
											break;
											
										default:
											# code...
											break;
									}
								?></td>

								<?php $i++; ;?>
							</tr>
							@endforeach
							<tr>
								<td colspan="10" class="text-center">
									<div class="row">
										{{$paginate->links()}}
									</div>
								</td>
							</tr>
							@else
							<tr>
								<th colspan="4" class="text-center">
									You have not any Fixing Shops , lets to <a href="{{route('fixing_shops.create')}}">add new Fixing Shops</a>
								</th>
							</tr>
							@endif
						</tbody>	
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/notifications/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						<b>{{$fixing_shops->shop_name}}</b>
					</div>
				</div>
				<div class="panel-body">
					<table class="table">
						<!-- English Content -->
						
						<tr>
							<th class="active">Arabic Name</th>
							<td>
								{{$fixing_shops->shop_name_ar}}
							</td>
						</tr>
						<tr>
							<th class="active">English Name</th>
							<td>
								{{$fixing_shops->shop_name_en}}
							</td>
						</tr>
						


						<tr>
							<th class="active">Logo</th>
							<td>
								<?php if ($fixing_shops->images != "" || $fixing_shops->images != NULL) {?> 
						<div class="col-md-3 col-lg-3 " align="center"> <img style="height: 100px;width: 100px" alt="User Pic" src="<?php echo $fixing_shops->images;?>" class="img-circle img-responsive"> </div>
						
						<?php }else{?>
						<div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://via.placeholder.com/300x300" class="img-circle img-responsive"> </div>
					<?php } ?>
							</td>
						</tr>

					    <tr>
							<th class="active">Slider Images</th>
							<td>
								<?php if (!empty($fixing_shops->sliders)) {
									foreach ($fixing_shops->sliders as $image) {?> 
						<div class="col-md-3 col-lg-3 " align="center"> <img style="height: 100px;width: 100px" alt="User Pic" src="<?php echo $image;?>" class="img-circle img-responsive"> </div>
						
						<?php } }?>

							</td>
						</tr>

						<tr>
							<th class="active">Type</th>
							<td><?php
									switch ($fixing_shops->fixing_shops_types_id) {
										case 1:
											echo "Gold";
											break;
										case 2:
											echo "Silver";
											break;
										case 3:
											echo "Bronze";
											break;
											
										default:
											# code...
											break;
									}
								?></td>
						</tr>
						
						<tr>
							<th class="active">English Details</th>
							<td>
								{{ strip_tags($fixing_shops->about_en)}}
							</td>
						</tr>
						

						<tr>
							<th class="active">Arabic Details</th>
							<td>
								{{ strip_tags($fixing_shops->about_ar)}}
							</td>
						</tr>
						
						<tr>
							<th class="active">Mobile</th>
							<td>
								{{$fixing_shops->mobile}}
							</td>
						</tr>

						<tr>
							<th class="active">Email</th>
							<td>
								{{$fixing_shops->email}}
							</td>
						</tr>

						<tr>
							<th class="active">City</th>
							<td>
								{{$City->name_en}}
							</td>
						</tr>

							<tr>
							<th class="active">English Address</th>
							<td>
								{{$fixing_shops->address_en}}
							</td>
						</tr>


						<tr>
							<th class="active">Arabic Address</th>
							<td>
								{{$fixing_shops->address_ar}}
							</td>
						</tr>


						<tr>
							<th class="active">Location</th>
							<td>
								{{$fixing_shops->location}}
							</td>
						</tr>


						<tr>
							<td colspan="2">
								<div class="row">
									<div class="col-sm-2">
										<a href="{{route('fixing_shops.index')}}" class="btn btn-block btn-default">Back</a>
									</div>
									<div class="col-sm-10">
										<div class="row">
											<div class="col-sm-9">
												<a class="btn btn-block btn-warning" href="{{route('fixing_shops.edit',$fixing_shops->id)}}">Edit</a>
											</div>	
											<div class="col-sm-3">
												<form method="POST" action="{{action('Web\FixingShopsController@destroy', $fixing_shops->id)}}">
															<input type="hidden" name="_method" value="delete" />
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
															<button class="btn-block btn btn-danger" onclick="return confirm('Are you sure to delete this Category?')">Delete</button>
												</form>
											</div>
										</div>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection