routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\AdminController@index');
Route::get('/verify/{token}', 'V1\RegisterController@verify')->name('verify');
Auth::routes();

Route::get('/firebase', 'Web\FirebaseController@index');
Route::get('/check_location', 'Web\CoveredAreasController@check_location');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reset/{token}', 'V1\LoginController@reset')->name('reset');
Route::post('/reset', 'V1\LoginController@doReset')->name('do.reset');

Route::group(['prefix' => 'admin', 'middleware' => 'MultiTenant'], function () {
    Route::group(['prefix' => '/'], function () {
        Route::get('/', 'Web\AdminController@index')->name('dashboard');
        Route::get('update_language/{id}', 'Web\AdminController@update_language')->name('update_language');
        Route::get('update_language_dashboard/{id}', 'Web\AdminController@update_language_dashboard')->name('update_language_dashboard');
        Route::get('/profile', 'Web\AdminController@profile')->name('profile');
        Route::post('update/{id}', 'Web\AdminController@update')->name('admin.update');
        Route::get('/edit/{id}', 'Web\AdminController@edit')->name('admin.edit');
        Route::get('/login', 'Web\AdminController@login')->name('login');
        Route::post('/doLogin', 'Web\AdminController@doLogin')->name('doLogin');
        Route::get('/logout', 'Web\AdminController@logout')->name('admin_logout');
        Route::get('/trips', 'Web\AdminController@trips')->name('trips');
        Route::get('/trips/{id}', 'Web\AdminController@show')->name('trip_show');
        Route::get('/shipments', 'Web\AdminController@shipments')->name('shipments');
        Route::get('/shipments/{id}', 'Web\AdminController@show_shipment')->name('shipment_show');
    });
    Route::resource('/deals', 'Web\DealController');
    Route::post('/deals/{id}/change_status', 'Web\DealController@change_status');
    Route::resource('/contact_us', 'Web\ContactUsController');
    Route::post('/contact_us/{id}/change_status', 'Web\ContactUsController@change_status');
    Route::resource('/cms', 'Web\CMSController');

    Route::resource('/company_ads', 'Web\CompanyAdsController');
    Route::resource('/company_profile', 'Web\CompanyProfileController');
    Route::resource('/company_branches', 'Web\CompanyBranchController');

    Route::resource('/covered_areas', 'Web\CoveredAreasController');
    Route::get('create_covered_area', 'Web\CoveredAreasController@create_covered_area');

    Route::resource('/fixing_shops', 'Web\FixingShopsController');

    Route::resource('/cities', 'Web\CityController');
    Route::resource('/notifications', 'Web\NotificationsController');

    Route::resource('/users_push_setting', 'Web\PushController');

    Route::resource('/category_groups', 'Web\CategoryGroupController');
    Route::resource('/problem_types', 'Web\ProblemTypesController');
    Route::resource('/sos_requests', 'Web\SOSRequestsController');
    Route::get('show_on_map/{id}', 'Web\SOSRequestsController@show_on_map');

    Route::resource('/company_types', 'Web\CompanyTypesController');


    Route::resource('/emergency', 'Web\EmergencyController');

    Route::resource('/categories', 'Web\CategoryController');

    Route::resource('/admin_ads', 'Web\AdsController');

    Route::resource('/app_ads', 'Web\AppAdsController');

    Route::resource('/user', 'Web\UserController');
    Route::get('/user/{id}/trips', 'Web\UserController@trips');
    Route::get('/user/{id}/shipments', 'Web\UserController@shipments');
    Route::post('/user/{id}/add-role', 'Web\UserController@addRole');
    Route::resource('/faq', 'Web\FaqController');
    Route::resource('/contacts', 'Web\ContactsController');
    Route::resource('/settings', 'Web\SettingsController');
});

app/Http/Controllers/V1/AppAdsController.php
<?php

namespace App\Http\Controllers\V1;

use App\Helpers\ResponseHandler;
use App\Http\Controllers\Controller;
use App\Http\Requests\AppAds\AppAdsRequest;
use App\Http\Resources\AppAds\AppAdsCollection;
use App\Http\Resources\AppAds\AppAdsResource;
use App\Model\AppAds;
use Carbon\Carbon;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class AppAdsController extends Controller
{
    /**
     * apply admin.perms
     */

    public function __construct()
    {
        $this->middleware('auth:api');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = [];
        $user = $request->user();
        $filter['company_id'] = $user->id;
        return ResponseHandler::jsonCollection(AppAdsCollection::collection(AppAds::where($filter)->orderby('created_at', 'desc')->get()));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AppAdsRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(AppAdsRequest $request)
    {
        $ads = $request->all();
        if ($request->hasFile('images')) {
            foreach ($request->file('images') as $image) {
                $file = $image;
                $image_name = time() . '_' . str_random(5) . '.' . $file->getClientOriginalExtension();
                if ($file->move(storage_path('app/public/ads/'), $image_name)) {
                    $images[] = "ads/" . $image_name;
                }

            }
        }

        $ads['images'] = json_encode($images);

        $ads = AppAds::create($ads);
        if (!$ads) {
            return ResponseHandler::json(false);
        } else {

            return ResponseHandler::json(
                new AppAdsResource($ads)
            );
            //return ResponseHandler::json(
            //        new AppAdsResource($ads),Response::HTTP_CREATED);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ads = AppAds::find($id);
        if (!$ads) {
            return ResponseHandler::json(false);
        } else {
            return ResponseHandler::json(
                new AppAdsResource($ads)
            );
            //return response([new AppAdsResource($admin_ads)],Response::HTTP_OK);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return void
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = $request->user();
        if (!$user) {
            throw new AuthenticationException;
        }

        $admin_ads = AppAds::where(['id' => $id, 'company_id' => $user->id])->first();
        //return $admin_ads;
        if (!$admin_ads) {
            return ResponseHandler::json(false);
        } else {
            $ads = $request->all();
            if ($request->hasFile('images') && !empty($request->file('images'))) {
                foreach ($request->file('images') as $image) {
                    $file = $image;
                    $image_name = time() . '_' . str_random(5) . '.' . $file->getClientOriginalExtension();
                    if ($file->move(storage_path('app/public/ads/'), $image_name)) {
                        $images[] = "ads/" . $image_name;
                    }

                }
                $ads['images'] = json_encode($images);
            } else {
                unset($ads['images']);
            }

            $ads['approved_status'] = NULL;
            $admin_ads->update($ads);
            //return $admin_ads;
            return ResponseHandler::json(
                new AppAdsResource($admin_ads)
            );
        }
    }

    public function republish(Request $request, $id)
    {
        $user = $request->user();
        if (!$user) {
            throw new AuthenticationException;
        }

        $admin_ads = AppAds::where(['id' => $id, 'company_id' => $user->id])->first();

        if (!$admin_ads) {
            return ResponseHandler::json(false);
        }

        $now = Carbon::now();
        $ads['created_at'] = $now;
        $admin_ads->update($ads);

        return ResponseHandler::json(
            new AppAdsResource($admin_ads)
        );

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $admin_ads = AppAds::find($id);
        if (!$admin_ads) {
            return ResponseHandler::json([false]);
        } else {
            $deleted = $admin_ads->delete();
            return response(['is_delete' => $deleted], Response::HTTP_OK);
        }
    }


}

resources/views/admin/app_ads/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
                        @lang('labels.admin.create_new_admin_ads')	
					</div>
				</div>
				<div class="panel-body">
					<form  enctype="multipart/form-data" method="POST" action="{{route('admin_ads.store')}}">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<!-- cms type -->
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.title')</label>
						    <div class="col-sm-10" {{ $errors->has('title') ? ' has-error' : '' }}>
						    	@if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="title" placeholder="@lang('labels.please_enter') @lang('labels.title')"  required/>
						    </div>
						  </div>
					  
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.ads_details')</label>
					    <div class="col-sm-10">
					    	<textarea class="form-control" placeholder="@lang('labels.ads_details')" name="details" ></textarea>
					    </div>
					  </div>

					  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.ads_image')</label>
					    <div class="col-sm-10">
					    	<input type="file" class="form-control" placeholder="@lang('labels.ads_image')" name="images" >
					    </div>
					  </div>

					  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.active')</label>
					    <div class="col-sm-10">
					    	<select class="form-control" name="active" >
										<option value="0">@lang('labels.admin.not_active')</option>
										<option value="1">@lang('labels.admin.active')</option>
									</select>
					    </div>
					  </div>

					  <!-- cms type -->
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.order')</label>
						    <div class="col-sm-10" {{ $errors->has('ordering') ? ' has-error' : '' }}>
						    	@if ($errors->has('ordering'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ordering') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="ordering" placeholder="@lang('labels.please_enter') @lang('labels.admin.ordering')"  required/>
						    </div>
						  </div>
					  
					  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.is_offer')</label>
					    <div class="col-sm-10">
					    	<select class="form-control" name="is_offer" >
										<option value="0">@lang('labels.not_offer')</option>
										<option value="1">@lang('labels.offer')</option>
									</select>
					    </div>
					  </div>


					   <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.is_banner')</label>
					    <div class="col-sm-10">
					    	<select class="form-control" name="is_banar" >
										<option value="0">@lang('labels.admin.not_banner')</option>
										<option value="1">@lang('labels.admin.first_banner')</option>
										<option value="2">@lang('labels.admin.second_banner')</option>
										<option value="3">@lang('labels.admin.third_banner')</option>
										<option value="4">@lang('labels.admin.fourth_banner')</option>
									</select>
					    </div>
					  </div>

					    <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.ads_display_on')</label>
					    <div class="col-sm-10">
					    	<select class="form-control" name="fixing_shops_or_home" >
										<option value="0">@lang('labels.admin.fixing_shops')</option>
										<option value="1">@lang('labels.admin.home_page')</option>
									</select>
					    </div>
					  </div>

					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
					   		<a href="{{route('admin_ads.index')}}" class="btn btn-default btn-block">@lang('labels.back')</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">@lang('labels.create')</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/app_ads/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
					    @lang('labels.admin.edit_ads_publisher') : {{$user->full_name}}
					</div>
				</div>
				<div class="panel-body">
					<form method="POST" action="{{action('Web\AppAdsController@update', $app_ads->id)}}">
						<input type="hidden" name="_method" value="put" />
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<!-- cms type -->

						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.title')</label>
						    <div class="col-sm-10" {{ $errors->has('title') ? ' has-error' : '' }}>
						    	@if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
						    	<input readonly type="text" class="form-control" name="title" placeholder="@lang('labels.please_enter') @lang('labels.title')" value="{{$app_ads->title}}" required/>
						    </div>
						  </div>
					  
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.ads_details')</label>
					    <div class="col-sm-10">
					    	<textarea readonly class="form-control" placeholder="@lang('labels.ads_details')" name="details" >{{$app_ads->details}}</textarea>
					    </div>
					  </div>

					  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.ads_image')</label>
					    <div class="col-sm-10">
					    	<input disabled="" type="file" class="form-control" placeholder="@lang('labels.ads_image')" name="images">
					    </div>
					  </div>

					  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label"> @lang('labels.select_cat')</label>
					    <div class="col-sm-10">
					    	<select disabled="" required name="category_id" class="form-control">
					    		
					    	<?php 
					    	if(!empty($categories)){
					    		foreach ($categories as $category) {
					    			?>
					    	<option <?php if($app_ads->category_id == $category->id)echo "selected"?> value="<?php echo $category->id?>"><?php echo $category->category_name?></option>
					    	<?php 	}
					    	}
					    	?>
					    	</select>
					    </div>
					  </div>
					  
					<!-- cms type -->
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.price')</label>
						    <div class="col-sm-10" {{ $errors->has('price') ? ' has-error' : '' }}>
						    	@if ($errors->has('price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
						    	<input readonly value="<?php echo $app_ads->price;?>" type="text" class="form-control" name="price" placeholder="@lang('labels.price')"  required/>
						    </div>
						  </div>

					 <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.used_status')</label>
					    <div class="col-sm-10">
					    	<select disabled="" required name="used_status" class="form-control">
					    		<option <?php if($app_ads->used_status == 0)echo "selected"?> value="0">@lang('labels.no')</option>
					    		<option <?php if($app_ads->used_status == 1)echo "selected"?> value="1">@lang('labels.yes')</option>
					    	
					    	</select>
					    </div>
					  </div>
					  

					  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.approval_status')</label>
					    <div class="col-sm-10">
					    	<select required name="approved_status" class="form-control">
					    		<option <?php if($app_ads->approved_status == 0)echo "selected"?> value="0">@lang('labels.no')</option>
					    		<option <?php if($app_ads->approved_status == 1)echo "selected"?> value="1">@lang('labels.yes')</option>
					    	
					    	</select>
					    </div>
					  </div>

<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.block_reason')</label>
						    <div class="col-sm-10" {{ $errors->has('block_reason') ? ' has-error' : '' }}>
						    	@if ($errors->has('block_reason'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('block_reason') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="block_reason" placeholder="@lang('labels.please_enter') @lang('labels.block_reason')" value="{{$app_ads->block_reason}}" />
						    </div>
						  </div>

					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
					   		<a href="{{route('app_ads.show',$app_ads->id)}}" class="btn btn-default btn-block">@lang('labels.back')</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">@lang('labels.update')</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/app_ads/search.blade.php
<div class="row">
	<div class="col-sm-12">
		<form method="" action="">
			<table class="table">
				<tbody>
					<tr>
						<td>
							<div class="row">
								<!-- name -->
								<div class="col-sm-4">
									<input type="text" name="title" class="form-control" placeholder=" @lang('labels.title') " value="{{Request::get('title')}}" />
								</div>

								<!-- email -->
								<div class="col-sm-4">
									<input type="text" name="owner" class="form-control" placeholder=" @lang('labels.owner_name') " value="{{Request::get('owner')}}" />
								</div>

								<!-- register type -->
								<div class="col-sm-4">
										
											<select name="user_types_id" class="form-control">
												<option value=""> @lang('labels.admin.select_membership_type')</option>
												
												<?php
												foreach ($user_types as $type) {?>
													<option value="<?php echo $type->id;?>" <?php if (Request::get('user_types_id') == $type->id) {echo "selected";}   ?>
														><?php echo $type->type_name;?></option>
												<?php }
												?>
												
												
											</select>
									
								</div>

								
							</div>
						</td>
					</tr>

					<tr>
						<td>
							<div class="row">
								<!-- name -->
								<div class="col-sm-4">
									<input type="text" onfocus="(this.type='date')" name="from" class="form-control" placeholder="@lang('labels.choose_date_from')" value="{{Request::get('from')}}" />
								</div>

								<!-- email -->
								<div class="col-sm-4">
									<input type="text" onfocus="(this.type='date')" name="to" class="form-control" placeholder="@lang('labels.choose_date_to')" value="{{Request::get('to')}}" />
								</div>
						
						<div class="col-sm-4">
									
											<select name="approved_status" class="form-control">
												<option value=""  {{(Request::get('approved_status') == "") ? 'selected' : ''}}>@lang('labels.select_approved_status')</option>
												{{-- <option value="2"  {{(Request::get('approved_status') == "2") ? 'selected' : ''}}>New</option> --}}
												<option value="0" {{(Request::get('approved_status') == '0') ? 'selected' : ''}}>@lang('labels.no')</option>
												<option value="1" {{(Request::get('approved_status') == '1') ? 'selected' : ''}}>@lang('labels.yes')</option>
											</select>
									
								</div>
								
							</div>
						</td>
					</tr>

					
					<tr>
						<td class="text-center" colspan="2">
							<div class="row">
								<div class="col-sm-6">
									<button type="submit" class="btn btn-primary px-4 col-sm-6"> @lang('labels.search') </button>
								</div>
								<div class="col-sm-6">
									<a style="float:right;" class="btn btn-danger px-4 col-sm-6" href="{{route('app_ads.index')}}"> @lang('labels.reset')</a>
								</div>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
</div>

resources/views/admin/app_ads/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						<b>{{$app_ads->title}}</b>
					</div>
				</div>
				<div class="panel-body">
					<table class="table">
						<!-- English Content -->
						
						<tr>
							<th class="active"> @lang('labels.owner') </th>
							<td>
								{{$user->full_name}}
							</td>
						</tr>

						<tr>
							<th class="active">@lang('labels.title')</th>
							<td>
								{{$app_ads->title}}
							</td>
						</tr>
						<tr>
							<th class="active">@lang('labels.details')</th>
							<td>
								{{ strip_tags($app_ads->details)}}
							</td>
						</tr>
						
						<tr>
							<th class="active">@lang('labels.ads_image')</th>
							<td>
								<?php if (!empty($app_ads->images)) {
									foreach ($app_ads->images as $image) {?> 
						<div class="col-md-3 col-lg-3 " align="center"> <img style="height: 100px;width: 100px" alt="User Pic" src="<?php echo $image;?>" class="img-circle img-responsive"> </div>
						
						<?php } }?>

							</td>
						</tr>

						<tr>
							<th class="active">@lang('labels.approval_status')</th>
							<td>
								
								{{($app_ads->approved_status) ? 'Yes' : 'No'}}
							</td>
						</tr>
					

						<tr>
							<th class="active">@lang('labels.posted_at')</th>
							<td>{{$app_ads->created_at}}</td>
						</tr>


						<tr>
							<th class="active">@lang('labels.used_status')</th>
							<td>
								
								{{($app_ads->used_status) ? 'Yes' : 'No'}}
							</td>
						</tr>
						<tr>
							<th class="active">@lang('labels.price')</th>
							<td>
								{{$app_ads->price}}
							</td>
						</tr>

						<tr>
							<th class="active">@lang('labels.block_reason')</th>
							<td>
								{{$app_ads->block_reason}}
							</td>
						</tr>


						<tr>
							<td colspan="2">
								<div class="row">
									<div class="col-sm-2">
										<a href="{{route('app_ads.index')}}" class="btn btn-block btn-default">@lang('labels.back')</a>
									</div>
									<div class="col-sm-10">
										<div class="row">
											<div class="col-sm-3">
												<a class="btn btn-block btn-warning" href="{{route('app_ads.edit',$app_ads->id)}}">@lang('labels.block')</a>
											</div>
											<div class="col-sm-6">
												<form method="POST" action="{{action('Web\AppAdsController@destroy', $app_ads->id)}}">
															<input type="hidden" name="_method" value="delete" />	
															<input type="hidden" name="approval" value="approval" />
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
															<button class="btn-block btn btn-danger" onclick="return confirm('Are you sure to Approve this Company Ads?')">@lang('labels.approval')</button>
												</form>
											</div>	
											<div class="col-sm-3">
												<form method="POST" action="{{action('Web\AppAdsController@destroy', $app_ads->id)}}">
															<input type="hidden" name="_method" value="delete" />
															<input type="hidden" name="approval" value="delete" />
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
															<button class="btn-block btn btn-danger" onclick="return confirm('Are you sure to delete this Company Ads?')">@lang('labels.delete')</button>
												</form>
											</div>
										</div>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection