routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\AdminController@index');
Route::get('/verify/{token}', 'V1\RegisterController@verify')->name('verify');
Auth::routes();

Route::get('/firebase', 'Web\FirebaseController@index');
Route::get('/check_location', 'Web\CoveredAreasController@check_location');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reset/{token}', 'V1\LoginController@reset')->name('reset');
Route::post('/reset', 'V1\LoginController@doReset')->name('do.reset');

Route::group(['prefix' => 'admin', 'middleware' => 'MultiTenant'], function () {
    Route::group(['prefix' => '/'], function () {
        Route::get('/', 'Web\AdminController@index')->name('dashboard');
        Route::get('update_language/{id}', 'Web\AdminController@update_language')->name('update_language');
        Route::get('update_language_dashboard/{id}', 'Web\AdminController@update_language_dashboard')->name('update_language_dashboard');
        Route::get('/profile', 'Web\AdminController@profile')->name('profile');
        Route::post('update/{id}', 'Web\AdminController@update')->name('admin.update');
        Route::get('/edit/{id}', 'Web\AdminController@edit')->name('admin.edit');
        Route::get('/login', 'Web\AdminController@login')->name('login');
        Route::post('/doLogin', 'Web\AdminController@doLogin')->name('doLogin');
        Route::get('/logout', 'Web\AdminController@logout')->name('admin_logout');
        Route::get('/trips', 'Web\AdminController@trips')->name('trips');
        Route::get('/trips/{id}', 'Web\AdminController@show')->name('trip_show');
        Route::get('/shipments', 'Web\AdminController@shipments')->name('shipments');
        Route::get('/shipments/{id}', 'Web\AdminController@show_shipment')->name('shipment_show');
    });
    Route::resource('/deals', 'Web\DealController');
    Route::post('/deals/{id}/change_status', 'Web\DealController@change_status');
    Route::resource('/contact_us', 'Web\ContactUsController');
    Route::post('/contact_us/{id}/change_status', 'Web\ContactUsController@change_status');
    Route::resource('/cms', 'Web\CMSController');

    Route::resource('/company_ads', 'Web\CompanyAdsController');
    Route::resource('/company_profile', 'Web\CompanyProfileController');
    Route::resource('/company_branches', 'Web\CompanyBranchController');

    Route::resource('/covered_areas', 'Web\CoveredAreasController');
    Route::get('create_covered_area', 'Web\CoveredAreasController@create_covered_area');

    Route::resource('/fixing_shops', 'Web\FixingShopsController');

    Route::resource('/cities', 'Web\CityController');
    Route::resource('/notifications', 'Web\NotificationsController');

    Route::resource('/users_push_setting', 'Web\PushController');

    Route::resource('/category_groups', 'Web\CategoryGroupController');
    Route::resource('/problem_types', 'Web\ProblemTypesController');
    Route::resource('/sos_requests', 'Web\SOSRequestsController');
    Route::get('show_on_map/{id}', 'Web\SOSRequestsController@show_on_map');

    Route::resource('/company_types', 'Web\CompanyTypesController');


    Route::resource('/emergency', 'Web\EmergencyController');

    Route::resource('/categories', 'Web\CategoryController');

    Route::resource('/admin_ads', 'Web\AdsController');

    Route::resource('/app_ads', 'Web\AppAdsController');

    Route::resource('/user', 'Web\UserController');
    Route::get('/user/{id}/trips', 'Web\UserController@trips');
    Route::get('/user/{id}/shipments', 'Web\UserController@shipments');
    Route::post('/user/{id}/add-role', 'Web\UserController@addRole');
    Route::resource('/faq', 'Web\FaqController');
    Route::resource('/contacts', 'Web\ContactsController');
    Route::resource('/settings', 'Web\SettingsController');
});

app/Http/Controllers/V1/FixingShopsController.php
<?php

namespace App\Http\Controllers\V1;

use App\Helpers\ResponseHandler;
use App\Http\Controllers\Controller;
use App\Http\Resources\FixingShops\FixingShopsCollection;
use App\Http\Resources\FixingShops\FixingShopsResource;
use App\Http\Resources\Home\MainSlidersCollection;
use App\Http\Resources\Home\MainSlidersResource;
use Illuminate\Http\Request;


class FixingShopsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $response = [
            'fixing_shops/main_sliders/',
            'fixing_shops/offers_sliders/',
            'fixing_shops/gold_fixing_shops/',
            'fixing_shops/first_banners/',
            'fixing_shops/silver_fixing_shops/',
            'fixing_shops/second_banners/',
            'fixing_shops/bronze_fixing_shops/',
            'fixing_shops/third_banners/',

        ];
        return ResponseHandler::json($response);
    }


    public function main_sliders($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\AdminAds::where(['fixing_shops_or_home' => 0,
            'active' => 1, 'is_banar' => 1])->count();
        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }

        $current_page = (int)($page_number);

        $main_sliders = \App\Model\AdminAds::where(['fixing_shops_or_home' => 0,
            'active' => 1, 'is_banar' => 1])
            ->orderby('ordering', 'desc')
            ->skip($offset)
            ->take($perpage)
            ->get();


        $response = MainSlidersCollection::collection($main_sliders);
        return ResponseHandler::json($response, $current_page, $lastPage);
    }


    public function main_slider_show($id)
    {
        $slider = \App\Model\AdminAds::find($id);
        if (!$slider) {
            return ResponseHandler::json([false]);
        } else {
            $count = $slider->views_count + 1;
            $slider->update(['views_count' => $count]);
            return ResponseHandler::json(new MainSlidersResource($slider));
        }
    }

    public function fixing_shops_details($id, $user_id = NULL)
    {
        $fixing_shops = \App\Model\FixingShops::find($id);
        if (!$fixing_shops) {
            return ResponseHandler::json([false]);
        } else {
            $fixing_shops['user_id'] = $user_id;
            return ResponseHandler::json(new FixingShopsResource($fixing_shops));
        }
    }

    public function fixing_shops_search(Request $request, $page_number, $perpage)
    {

        $filter = $this->getFilter($request);
        $data = [];

        $simple_filter = (isset($filter['simple'])) ? $filter['simple'] : [];

        $name = (isset($filter['simple']['name'])) ? $filter['simple']['name'] : NULL;
        $type_id = (isset($filter['simple']['type_id'])) ? $filter['simple']['type_id'] : 0;
        unset($simple_filter['name']);
        unset($simple_filter['type_id']);

        $total = \App\Model\FixingShops::where($simple_filter);

        if ($name != NULL) {
            $total = $total->where('shop_name', 'LIKE', '%' . $name . '%');
            $total = $total->orwhere('shop_name_ar', 'LIKE', '%' . $name . '%');
        }


        if ($type_id != 0) {
            $total = $total->where('fixing_shops_types_id', $type_id);
        }

        $total = $total->count();

        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }

        $offset = $page_number * $perpage;
        $current_page = (int)$page_number;

        $main_sliders = \App\Model\FixingShops::where($simple_filter);
        if ($name != NULL) {
            $main_sliders = $main_sliders->where('shop_name', 'LIKE', '%' . $name . '%');
            $main_sliders = $main_sliders->orwhere('shop_name_ar', 'LIKE', '%' . $name . '%');
        }

        if ($type_id != 0) {
            $main_sliders = $main_sliders->where('fixing_shops_types_id', '=', $type_id);
        }
        $main_sliders = $main_sliders->skip($offset)
            ->take($perpage)
            ->get();

        $response = FixingShopsCollection::collection($main_sliders);
        //return $response;
        return ResponseHandler::json($response, $current_page, $lastPage);
    }


    public function getFilter(Request $request)
    {
        $filter = [];

        if ($request->has('name') && $request->get('name')) {
            $filter['simple']['name'] = $request->get('name');
        }

        if ($request->has('type_id') && null !== $request->get('type_id')) {
            $filter['simple']['type_id'] = $request->get('type_id');
        }

        return $filter;
    }


    public function offers_sliders($page_number, $perpage)
    {
        $offset = $page_number * $perpage;
        $total = \App\Model\AdminAds::where(['fixing_shops_or_home' => 0,
            'active' => 1, 'is_banar' => 2])->count();
        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }


        $current_page = (int)$page_number;


        $main_sliders = \App\Model\AdminAds::where(['fixing_shops_or_home' => 0,
            'active' => 1, 'is_banar' => 2])
            ->orderby('ordering', 'desc')
            ->skip($offset)
            ->take($perpage)
            ->get();


        $response = MainSlidersCollection::collection($main_sliders);
        return ResponseHandler::json($response, $current_page, $lastPage);
    }

    public function first_banners($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\AdminAds::where(['fixing_shops_or_home' => 0,
            'active' => 1, 'is_banar' => 3])->count();
        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }


        $current_page = (int)$page_number;

        $main_sliders = \App\Model\AdminAds::where(['fixing_shops_or_home' => 0,
            'active' => 1, 'is_banar' => 3])
            ->orderby('ordering', 'desc')
            ->skip($offset)
            ->take($perpage)
            ->get();
        $response = MainSlidersCollection::collection($main_sliders);
        return ResponseHandler::json($response, $current_page, $lastPage);
    }


    public function gold_fixing_shops($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\FixingShops::where([
            'fixing_shops_types_id' => 1])->count();

        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }
        $current_page = (int)$page_number;

        $main_sliders = \App\Model\FixingShops::where([
            'fixing_shops_types_id' => 1])
            ->skip($offset)
            ->take($perpage)
            ->get();
        $response = FixingShopsCollection::collection($main_sliders);
        return ResponseHandler::json($response, $current_page, $lastPage);
    }


    public function second_banners($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\AdminAds::where(['fixing_shops_or_home' => 1,
            'active' => 1, 'is_banar' => 4])->count();
        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }


        $current_page = (int)$page_number;

        $main_sliders = \App\Model\AdminAds::where(['fixing_shops_or_home' => 1,
            'active' => 1, 'is_banar' => 4])
            ->orderby('ordering', 'desc')
            ->skip($offset)
            ->take($perpage)
            ->get();
        $response = MainSlidersCollection::collection($main_sliders);
        return ResponseHandler::json($response, $current_page, $lastPage);
    }


    public function silver_fixing_shops($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\FixingShops::where([
            'fixing_shops_types_id' => 2])->count();

        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }
        $current_page = (int)$page_number;

        $main_sliders = \App\Model\FixingShops::where([
            'fixing_shops_types_id' => 2])
            ->skip($offset)
            ->take($perpage)
            ->get();
        $response = FixingShopsCollection::collection($main_sliders);
        return ResponseHandler::json($response, $current_page, $lastPage);
    }


    public function third_banners($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\AdminAds::where(['fixing_shops_or_home' => 1,
            'active' => 1, 'is_banar' => 5])->count();
        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }


        $current_page = (int)$page_number;

        $main_sliders = \App\Model\AdminAds::where(['fixing_shops_or_home' => 1,
            'active' => 1, 'is_banar' => 5])
            ->orderby('ordering', 'desc')
            ->skip($offset)
            ->take($perpage)
            ->get();
        $response = MainSlidersCollection::collection($main_sliders);
        return ResponseHandler::json($response, $lastPage, $current_page);
    }


    public function bronze_fixing_shops($page_number, $perpage)
    {
        $offset = $page_number * $perpage;

        $total = \App\Model\FixingShops::where([
            'fixing_shops_types_id' => 3])->count();

        if ($total <= $perpage) {
            $lastPage = 0;
        } else {
            $lastPage = ceil($total / $perpage) - 1;
        }

resources/views/admin/fixing_shops/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						@lang('labels.admin.create_fixing_shops')
					</div>
				</div>
				<div class="panel-body">
					<form  enctype="multipart/form-data" method="POST" action="{{route('fixing_shops.store')}}">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						
						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.eng_name')</label>
						    <div class="col-sm-10" {{ $errors->has('shop_name') ? ' has-error' : '' }}>
						    	@if ($errors->has('shop_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('shop_name') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="shop_name" placeholder="@lang('labels.please_enter') @lang('labels.eng_name')"  required/>
						    </div>
						  </div>
					  
					  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.ar_name')</label>
						    <div class="col-sm-10" {{ $errors->has('shop_name_ar') ? ' has-error' : '' }}>
						    	@if ($errors->has('shop_name_ar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('shop_name_ar') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="shop_name_ar" placeholder="@lang('labels.please_enter') @lang('labels.ar_name')"  required/>
						    </div>
						  </div>

					 

							
  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.Logo')</label>
					    <div class="col-sm-10">
					    	<input type="file" class="form-control" placeholder="@lang('labels.Logo')" name="images" required>
					    </div>
					  </div>

					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.slider_images')</label>
					    <div class="col-sm-10">
					    	<input type="file" class="form-control" placeholder="@lang('labels.slider_images')" name="sliders[]" multiple >
					    </div>
					  </div>

						
					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.type')</label>
					    <div class="col-sm-10">
						<select class="form-control" name="fixing_shops_types_id" required="">
						<?php 
						if(!empty($fixing_shops_types)){
							foreach ($fixing_shops_types as $type) {?>
								<option value="<?php echo $type->id?>"><?php echo $type->type_name?></option>
							<?php }
						}
						?>
						</select>
					    </div>
					  </div>


					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.eng_details')</label>
					    <div class="col-sm-10">
					    	<textarea class="form-control" placeholder="@lang('labels.admin.eng_details')" name="about" ></textarea>
					    </div>
					  </div>

					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.ar_details')</label>
					    <div class="col-sm-10">
					    	<textarea class="form-control" placeholder="@lang('labels.admin.ar_details')" name="about_ar" ></textarea>
					    </div>
					  </div>


					  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.phone')</label>
						    <div class="col-sm-10" {{ $errors->has('mobile') ? ' has-error' : '' }}>
						    	@if ($errors->has('mobile'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('mobile') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="mobile" placeholder="@lang('labels.please_enter') @lang('labels.admin.phone')"  required/>
						    </div>
						  </div>

						  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.email')</label>
						    <div class="col-sm-10" {{ $errors->has('email') ? ' has-error' : '' }}>
						    	@if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
						    	<input type="email" class="form-control" name="email" placeholder="@lang('labels.please_enter') @lang('labels.email')"  required/>
						    </div>
						  </div>

				 <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.city')</label>
					    <div class="col-sm-10">
						<select class="form-control" name="city_id" required="">
						<?php 
						if(!empty($cities)){
							foreach ($cities as $type) {?>
								<option value="<?php echo $type->id?>"><?php echo $type->name_en?></option>
							<?php }
						}
						?>
						</select>
					    </div>
					  </div>

					
					 <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.eng_address')</label>
						    <div class="col-sm-10" {{ $errors->has('address') ? ' has-error' : '' }}>
						    	@if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="address" placeholder="@lang('labels.please_enter') @lang('labels.admin.eng_address')"  required/>
						    </div>
						  </div>

				 <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.ar_address')</label>
						    <div class="col-sm-10" {{ $errors->has('address_ar') ? ' has-error' : '' }}>
						    	@if ($errors->has('address_ar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address_ar') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="address_ar" placeholder="@lang('labels.please_enter') @lang('labels.admin.ar_address')"  required/>
						    </div>
						  </div>
						  		  
		  
		   <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.location')</label>
						    <div class="col-sm-10" {{ $errors->has('location') ? ' has-error' : '' }}>
						    	@if ($errors->has('location'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('location') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="location" placeholder="@lang('labels.please_enter') @lang('labels.admin.location')"  required/>
						    </div>
						  </div>


					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
					   		<a href="{{route('fixing_shops.index')}}" class="btn btn-default btn-block">@lang('labels.back')</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">@lang('labels.create')</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/fixing_shops/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12 col-md-offset-0">
			<div class="panel panel-default">
				<div class="panel-heading">@lang('labels.admin.fixing_shops')</div>
				<div class="panel-body">
					@include('admin.fixing_shops.search')
					<table class="table table-hover">
						<thead>
							<tr>
								<td colspan="5">
									<a href="{{route('fixing_shops.create')}}" class="btn btn-primary">+ @lang('labels.admin.new_fixing_shops')</a>
								</td>
							</tr>
							<tr class="active">
								<th>#</th>
								<th>@lang('labels.ar_name')</th>
								<th>@lang('labels.eng_name')</th>
								<th>Type</th>
							</tr>
						</thead>
						<tbody>
								<?php 
								$page = (isset($_GET['page'])) ? $_GET['page'] : 0;
								$page = ($page > 0) ? ($page -1) : 0;
								$i = ($page*20)+1;
								?>
							@if(isset($fixing_shops) && !empty($fixing_shops))
							@foreach($fixing_shops as $page)
							<tr  onclick="window.location='{{route('fixing_shops.show',$page->id)}}';" style="cursor : pointer">
								<td><?php echo $i ;?></td>
								<td>{{$page->shop_name_ar}}</td>
								<td>{{$page->shop_name_en}}</td>
								<td><?php
									switch ($page->fixing_shops_types_id) {
										case 1:
											echo "Gold";
											break;
										case 2:
											echo "Silver";
											break;
										case 3:
											echo "Bronze";
											break;
											
										default:
											# code...
											break;
									}
								?></td>

								<?php $i++; ;?>
							</tr>
							@endforeach
							<tr>
								<td colspan="10" class="text-center">
									<div class="row">
										{{$paginate->appends(request()->input())->links()}}
									</div>
								</td>
							</tr>
							@else
							<tr>
								<th colspan="4" class="text-center">
									You have not any Fixing Shops , lets to <a href="{{route('fixing_shops.create')}}">@lang('labels.admin.new_fixing_shops')</a>
								</th>
							</tr>
							@endif
						</tbody>	
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/fixing_shops/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						<b>{{$fixing_shops->shop_name_en}}</b>
					</div>
				</div>
				<div class="panel-body">
					<table class="table">
						<!-- English Content -->
						
						<tr>
							<th class="active">@lang('labels.ar_name')</th>
							<td>
								{{$fixing_shops->shop_name_ar}}
							</td>
						</tr>
						<tr>
							<th class="active">@lang('labels.eng_name')</th>
							<td>
								{{$fixing_shops->shop_name_en}}
							</td>
						</tr>
						


						<tr>
							<th class="active">@lang('labels.Logo')</th>
							<td>
								<?php if ($fixing_shops->images != "" || $fixing_shops->images != NULL) {?> 
						<div class="col-md-3 col-lg-3 " align="center"> <img style="height: 100px;width: 100px" alt="User Pic" src="<?php echo $fixing_shops->images;?>" class="img-circle img-responsive"> </div>
						
						<?php }else{?>
						<div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://via.placeholder.com/300x300" class="img-circle img-responsive"> </div>
					<?php } ?>
							</td>
						</tr>

					    <tr>
							<th class="active">@lang('labels.slider_images')</th>
							<td>
								<?php if (!empty($fixing_shops->sliders)) {
									foreach ($fixing_shops->sliders as $image) {?> 
						<div class="col-md-3 col-lg-3 " align="center"> <img style="height: 100px;width: 100px" alt="User Pic" src="<?php echo $image;?>" class="img-circle img-responsive"> </div>
						
						<?php } }?>

							</td>
						</tr>

						<tr>
							<th class="active">@lang('labels.type')</th>
							<td><?php
									switch ($fixing_shops->fixing_shops_types_id) {
										case 1:
											echo "Gold";
											break;
										case 2:
											echo "Silver";
											break;
										case 3:
											echo "Bronze";
											break;
											
										default:
											# code...
											break;
									}
								?></td>
						</tr>
						
						<tr>
							<th class="active">@lang('labels.admin.eng_details')</th>
							<td>
								{{ strip_tags($fixing_shops->about_en)}}
							</td>
						</tr>
						

						<tr>
							<th class="active">@lang('labels.admin.ar_details')</th>
							<td>
								{{ strip_tags($fixing_shops->about_ar)}}
							</td>
						</tr>
						
						<tr>
							<th class="active">@lang('labels.mobile')</th>
							<td>
								{{$fixing_shops->mobile}}
							</td>
						</tr>

						<tr>
							<th class="active">@lang('labels.email')</th>
							<td>
								{{$fixing_shops->email}}
							</td>
						</tr>

						<tr>
							<th class="active">@lang('labels.city')</th>
							<td>
								{{$City->name_en}}
							</td>
						</tr>

							<tr>
							<th class="active">@lang('labels.admin.eng_address')</th>
							<td>
								{{$fixing_shops->address_en}}
							</td>
						</tr>


						<tr>
							<th class="active">@lang('labels.admin.ar_address')</th>
							<td>
								{{$fixing_shops->address_ar}}
							</td>
						</tr>


						<tr>
							<th class="active">@lang('labels.location_string')</th>
							<td>
								{{$fixing_shops->location}}
							</td>
						</tr>


						<tr>
							<td colspan="2">
								<div class="row">
									<div class="col-sm-2">
										<a href="{{route('fixing_shops.index')}}" class="btn btn-block btn-default">@lang('labels.back')</a>
									</div>
									<div class="col-sm-10">
										<div class="row">
											<div class="col-sm-9">
												<a class="btn btn-block btn-warning" href="{{route('fixing_shops.edit',$fixing_shops->id)}}">@lang('labels.edit')</a>
											</div>	
											<div class="col-sm-3">
												<form method="POST" action="{{action('Web\FixingShopsController@destroy', $fixing_shops->id)}}">
															<input type="hidden" name="_method" value="delete" />
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
															<button class="btn-block btn btn-danger" onclick="return confirm('Are you sure to delete this Category?')">@lang('labels.delete')</button>
												</form>
											</div>
										</div>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection