routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\AdminController@index');
Route::get('/verify/{token}', 'V1\RegisterController@verify')->name('verify');
Auth::routes();

Route::get('/firebase', 'Web\FirebaseController@index');
Route::get('/check_location', 'Web\CoveredAreasController@check_location');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reset/{token}', 'V1\LoginController@reset')->name('reset');
Route::post('/reset', 'V1\LoginController@doReset')->name('do.reset');

Route::group(['prefix' => 'admin', 'middleware' => 'MultiTenant'], function () {
    Route::group(['prefix' => '/'], function () {
        Route::get('/', 'Web\AdminController@index')->name('dashboard');
        Route::get('update_language/{id}', 'Web\AdminController@update_language')->name('update_language');
        Route::get('update_language_dashboard/{id}', 'Web\AdminController@update_language_dashboard')->name('update_language_dashboard');
        Route::get('/profile', 'Web\AdminController@profile')->name('profile');
        Route::post('update/{id}', 'Web\AdminController@update')->name('admin.update');
        Route::get('/edit/{id}', 'Web\AdminController@edit')->name('admin.edit');
        Route::get('/login', 'Web\AdminController@login')->name('login');
        Route::post('/doLogin', 'Web\AdminController@doLogin')->name('doLogin');
        Route::get('/logout', 'Web\AdminController@logout')->name('admin_logout');
        Route::get('/trips', 'Web\AdminController@trips')->name('trips');
        Route::get('/trips/{id}', 'Web\AdminController@show')->name('trip_show');
        Route::get('/shipments', 'Web\AdminController@shipments')->name('shipments');
        Route::get('/shipments/{id}', 'Web\AdminController@show_shipment')->name('shipment_show');
    });
    Route::resource('/deals', 'Web\DealController');
    Route::post('/deals/{id}/change_status', 'Web\DealController@change_status');
    Route::resource('/contact_us', 'Web\ContactUsController');
    Route::post('/contact_us/{id}/change_status', 'Web\ContactUsController@change_status');
    Route::resource('/cms', 'Web\CMSController');

    Route::resource('/company_ads', 'Web\CompanyAdsController');
    Route::resource('/company_profile', 'Web\CompanyProfileController');
    Route::resource('/company_branches', 'Web\CompanyBranchController');

    Route::resource('/covered_areas', 'Web\CoveredAreasController');
    Route::get('create_covered_area', 'Web\CoveredAreasController@create_covered_area');

    Route::resource('/fixing_shops', 'Web\FixingShopsController');

    Route::resource('/cities', 'Web\CityController');
    Route::resource('/notifications', 'Web\NotificationsController');

    Route::resource('/users_push_setting', 'Web\PushController');

    Route::resource('/category_groups', 'Web\CategoryGroupController');
    Route::resource('/problem_types', 'Web\ProblemTypesController');
    Route::resource('/sos_requests', 'Web\SOSRequestsController');
    Route::get('show_on_map/{id}', 'Web\SOSRequestsController@show_on_map');

    Route::resource('/company_types', 'Web\CompanyTypesController');


    Route::resource('/emergency', 'Web\EmergencyController');

    Route::resource('/categories', 'Web\CategoryController');

    Route::resource('/admin_ads', 'Web\AdsController');

    Route::resource('/app_ads', 'Web\AppAdsController');

    Route::resource('/user', 'Web\UserController');
    Route::get('/user/{id}/trips', 'Web\UserController@trips');
    Route::get('/user/{id}/shipments', 'Web\UserController@shipments');
    Route::post('/user/{id}/add-role', 'Web\UserController@addRole');
    Route::resource('/faq', 'Web\FaqController');
    Route::resource('/contacts', 'Web\ContactsController');
    Route::resource('/settings', 'Web\SettingsController');
});

app/Http/Controllers/Web/SettingsController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Model\Settings;
use Illuminate\Http\Request;

class SettingsController extends Controller
{

    public function __construct()
    {
        $this->middleware('is.admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $settings = Settings::all();
        $data['settings'] = $settings;
        return view('admin.settings.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $setting = Settings::create($request->all());
        return redirect(route('settings.show', $setting->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [];
        $setting = Settings::find($id);
        $data['setting'] = $setting;
        if (!$setting) {
            return redirect(route('settings.index'));
        }
        return view('admin.settings.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];
        $setting = Settings::find($id);
        $data['setting'] = $setting;
        if (!$setting) {
            return redirect(route('settings.index'));
        }
        return view('admin.settings.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $setting = Settings::find($id);
        if (!$setting) {
            return redirect(route('settings.index'));
        }
        $setting->update($request->all());
        return redirect(route('settings.show', $id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return void
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/setting/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
                        @lang('labels.admin.create_category')
                    </div>
				</div>
				<div class="panel-body">
					<form  enctype="multipart/form-data" method="POST" action="{{route('categories.store')}}">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<!-- cms type -->
						
  <!-- content image -->
					  <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.category_icon')</label>
					    <div class="col-sm-10">
					    	<input type="file" class="form-control" placeholder="@lang('labels.admin.category_icon')" name="icon" required>
					    </div>
					  </div>

						<div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.eng_cat_name')</label>
						    <div class="col-sm-10" {{ $errors->has('category_name') ? ' has-error' : '' }}>
						    	@if ($errors->has('category_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category_name') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="category_name" placeholder="@lang('labels.please_enter') @lang('labels.admin.eng_cat_name')"  required/>
						    </div>
						  </div>
					  
					  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.ar_cat_name')</label>
						    <div class="col-sm-10" {{ $errors->has('category_name_ar') ? ' has-error' : '' }}>
						    	@if ($errors->has('category_name_ar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category_name_ar') }}</strong>
                                    </span>
                                @endif
						    	<input type="text" class="form-control" name="category_name_ar" placeholder="@lang('labels.please_enter') @lang('labels.admin.ar_cat_name')"  required/>
						    </div>
						  </div>

					 
					   <div class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.cat_type')</label>
					    <div class="col-sm-10">
					<label class="radio-inline">
                  <input required type="radio" value="1" name="category_type" >@lang('labels.admin.user_cat')
                    </label>
			    <label class="radio-inline">
			      <input required type="radio" value="3" name="category_type" checked>@lang('labels.admin.company_cat')
			    </label>
			    <label class="radio-inline">
			      <input required type="radio" value="2" name="category_type"> Both
			    </label>
					    </div>
					  </div>

						
					  <div id="category_group_id" class="form-group row">
					    <label for="inputPassword" class="col-sm-2 col-form-label">@lang('labels.admin.cat_group')</label>
					    <div class="col-sm-10">
					    	<select required name="category_group_id" class="form-control">
					    	<option value="0">@lang('labels.admin.select_cat_group')</option>	
					    	<?php 
					    	if(!empty($groups)){
					    		foreach ($groups as $group) {
					    			?>
					    	<option value="<?php echo $group->id?>"><?php echo $group->group_name?></option>
					    	<?php 	}
					    	}
					    	?>
					    	</select>
					    </div>
					  </div>



					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
                            <a href="{{route('categories.index')}}" class="btn btn-default btn-block">@lang('labels.back')</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">@lang('labels.create')</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/setting/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
                        @lang('labels.admin.edit_user_push_notification')						
					</div>
				</div>
				<div class="panel-body">
					<form method="POST" enctype="multipart/form-data" action="{{action('Web\PushController@update', $categories->id)}}">
						<input type="hidden" name="_method" value="put" />
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<!-- cms type -->

					  

						  <div class="form-group row">
						    <label for="inputPassword" class="col-sm-4 col-form-label"># @lang('labels.admin.notification_per_month')</label>
						    <div class="col-sm-6" {{ $errors->has('number_of_notifications') ? ' has-error' : '' }}>
						    	@if ($errors->has('number_of_notifications'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('number_of_notifications') }}</strong>
                                    </span>
                                @endif
						    	<input type="number" class="form-control" name="number_of_notifications" placeholder="please enter # Notifications Per Month" value="{{$categories->number_of_notifications}}" required/>
						    </div>
						  </div>

					  

				


					   

					   <div class="form-group row">
					   	<label for="inputPassword" class="col-sm-2 col-form-label">
					   		<a href="{{route('users_push_setting.show',$categories->id)}}" class="btn btn-default btn-block">@lang('labels.back')</a>
					   	</label>
						    <div class="col-sm-10">
						    	<button class="btn btn-block btn-success">@lang('labels.update')</button>
						    </div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/setting/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12 col-md-offset-0">
			<div class="panel panel-default">
                <div class="panel-heading">
 @lang('labels.admin.user_push_settings')   </div>
				<div class="panel-body">
					
					<table class="table table-hover">
						<thead>
							{{-- <tr>
								<td colspan="5">
									<a href="{{route('users_push_setting.create')}}" class="btn btn-primary">+  @lang('labels.admin.new_category') </a>
								</td>
							</tr> --}}
							<tr class="active">
								<th>#</th>
								
								<th>#  @lang('labels.admin.notification_per_month')</th>
								
							</tr>
						</thead>
						<tbody>
							<?php $i = 1 ;?>
							@if(isset($categories) && !empty($categories))
							@foreach($categories as $page)
							<tr  onclick="window.location='{{route('users_push_setting.show',$page->id)}}';" style="cursor : pointer">
								<td><?php echo $i ;?></td>
								<td>{{$page->number_of_notifications}}</td>
								
								

								<?php $i++; ;?>
							</tr>
							@endforeach
							<tr>
								<td colspan="4" class="text-center">
									<div class="row">
										{{$paginate->appends(request()->input())->links()}}
									</div>
								</td>
							</tr>
							@else
							<tr>
								<th colspan="10" class="text-center">
									You have not any Setting , lets to <a href="{{route('users_push_setting.create')}}">add new Setting</a>
								</th>
							</tr>
							@endif
						</tbody>	
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/setting/search.blade.php
<div class="row">
	<div class="col-sm-12">
		<form method="" action="">
			<table class="table">
				<tbody>
					<tr>
						<td>
							<div class="row">
								

								<!-- name -->
								<div class="col-sm-4">
									<input type="text" name="name" class="form-control" placeholder="@lang('labels.admin.eng_cat_name')" value="{{Request::get('name')}}" />
								</div>

								<!-- name -->
								<div class="col-sm-4">
									<input type="text" name="name_ar" class="form-control" placeholder="@lang('labels.admin.ar_cat_name')" value="{{Request::get('name_ar')}}" />
								</div>


								<!-- register type -->
								<div class="col-sm-4">
									<div class="row">
										<div class="col-sm-6 lead"> @lang('labels.admin.cat_type')</div>
										<div class="col-sm-6">
											<select name="category_type" class="form-control">
												<option value="">Select</option>
												<option value="1" {{(Request::get('category_type') == '1') ? 'selected' : ''}}>User Type</option>
												
												<option value="3" {{(Request::get('category_type') == '3') ? 'selected' : ''}}>Company Type</option>
												
												<option value="2" {{(Request::get('category_type') == '2') ? 'selected' : ''}}>Both</option>

											</select>
										</div>
									</div>
								</div>

								

								
							</div>
						</td>
					</tr>

					
					<tr>
						<td class="text-center" colspan="2">
							<div class="row">
								<div class="col-sm-6">
                                    <button type="submit" class="btn btn-primary px-4 col-sm-6">@lang('labels.search')</button>
								</div>
								<div class="col-sm-6">
									<a style="float:right;" class="btn btn-danger px-4 col-sm-6" href="{{route('categories.index')}}">@lang('labels.reset')</a>
								</div>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
</div>

resources/views/admin/setting/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="row text-center">
						<b> @lang('labels.admin.user_push_notification_per_month') </b>
					</div>
				</div>
				<div class="panel-body">
					<table class="table">
						
						

						<tr>
							<th  class="active"># @lang('labels.admin.notification_per_month')</th>
							<td>
								{{$categories->number_of_notifications}}
							</td>
						</tr>
					
						

					

						<tr>
							<td >
								<div class="row">
									<div class="col-sm-2">
										<a href="{{route('users_push_setting.index')}}" class="btn btn-block btn-default">@lang('labels.back')</a>
									</div>
									<div class="col-sm-7">
										<div class="row">
											<div class="col-sm-7">
												<a class="btn btn-block btn-warning" href="{{route('users_push_setting.edit',$categories->id)}}">@lang('labels.edit')</a>
											</div>	
											{{-- <div class="col-sm-3">
												<form method="POST" action="{{action('Web\CategoryController@destroy', $categories->id)}}">
															<input type="hidden" name="_method" value="delete" />
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
															<button class="btn-block btn btn-danger" onclick="return confirm('Are you sure to delete this Category?')">@lang('labels.delete')</button>
												</form>
											</div> --}}
										</div>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection